version: '3'

networks:
  backendservices:

services:
  # -------------------------------------------------------
  # Databases
  # -------------------------------------------------------
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gtfs
      MYSQL_USER: gtfs
      MYSQL_PASSWORD: secret
    volumes:
      - ./gtfs:/tmp/data
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql
      - persistent:/var/lib/mysql
    networks:
      - backendservices
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - backendservices

volumes:
    persistent:
